<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTXCQ4nu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTXCQ4nu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTXCQ4nu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTXCQ4nu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTXCQ4nu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TXCQ4nu',
    'container.build_id' => 'd31ff786',
    'container.build_time' => 1560243719,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTXCQ4nu');
